version: "3.8"
services:
#  grafana:
#    image: grafana/grafana-oss
#    ports: 
#      - 3000:3000
#    container_name: grafana
#    restart: unless-stopped
#    environment:
#      - VIRTUAL_HOST=${VIRTUAL_HOST}
#      - VIRTUAL_PORT=${VIRTUAL_PORT}
#    volumes:
#      - grafana-storage:/var/lib/grafana
#    networks:
#      - db-backend
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      db-backend:
        aliases:
          - db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    labels:
      logging: "promtail"
      logging_jobname: "pv-monitor-db"
  worker:
    build: 
      context: .
      dockerfile: worker/Dockerfile
    restart: unless-stopped
    networks:
      - db-backend
    depends_on:
      - db
    labels:
      logging: "promtail"
      logging_jobname: "pv-monitor-worker"
    # devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"
    #  - "/dev/ttyUSB1:/dev/ttyUSB1"

volumes:
#  grafana-storage: {}
  pgdata: {}
networks:
  db-backend:
